version: '1'
services:
  chain-node:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config.toml
    volumes:
      - ../parity:/parity
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      backend:
        ipv4_address: 172.15.0.12
