version: '3'
services:
  chain-node:
    image: ethereum/client-go:latest
    command:

    volumes:
      - ../parity:/parity
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.33.0.10
